name: release

on:
  push:
    branches:
      - main
  # push:
  #   tags:
  #     - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Tag push
        id: tag_push
        run: |
          export TAG_NAME=$(sed -n 6P pubspec.yaml | sed 's/version: //')
          git tag 1.0.1
          git push origin 1.0.1
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}


