name: release

on:
  push:
    branches:
      - main
  # push:
  #   tags:
  #     - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Tag push
        id: tag_push
        run: |
          git tag ${{ steps.get_tag_name.outputs.TAG_NAME }}
          git push origin ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}


